apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: green-deployment
  labels:
    app: green
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: docker.io/jygogo/bgimage:green
        imagePullPolicy: Always
        ports:
        - containerPort: 80
