apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  labels:
    app: my-loadbalancer
spec:
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
