apiVersion: v1
kind: Service
metadata:
  name: my-loadBalancer
  labels:
    app: my-loadBalancer
spec:
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  clusterIP: 10.100.0.1
  type: LoadBalancer
